name: 'Depcheck action'
inputs:
    project:
        required: true
    path:
        required: true  
    format:
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:

        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format }}'
        - '--out'
        -  './reports'
