on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build project with Maven
      #   run: mvn clean install
      - name: Depcheck
        uses: ./
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
      - name: checkdir1
        run: ls -la
      - name: check file
        run: cat bar.txt
